name: ProShop CI

on: 
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest

        env:
            RDS_DB_NAME: ${{ secrets.RDS_DB_NAME }}
            RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
            RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
            RDS_HOSTNAME: ${{ secrets.RDS_HOSTNAME }}

        strategy:
            matrix:
                python-version: [3.x]
                node-version: [16.x]

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Set up Python 
          uses: actions/setup-python@v5
          with:
            python-version: ${{ matrix.python-version }}
            cache: 'pip'

        - name: Install dependencies 
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Run tests
          run: python manage.py test

        - name: Set up Nodejs
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}

  
        - name: Install frontend dependencies
          working-directory: frontend
          # run: npm ci --legacy-peer-deps
          run: npm install

        - name: Lint Code
          working-directory: frontend
          run: npm run lint || true # Ignore failures

        - name: Build frontend
          working-directory: frontend
          env:
            CI: false
          run: |
           export DISABLE_ESLINT_PLUGIN=true
           npm run build --if-present 